"""test running migrations

Revision ID: 46f7ffdce330
Revises: 652beee47039
Create Date: 2024-03-05 19:33:37.482900

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "46f7ffdce330"
down_revision = "652beee47039"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
