"""test running migrations

Revision ID: 73ebee477f93
Revises: 94381e463511
Create Date: 2024-03-04 19:30:20.175806

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "73ebee477f93"
down_revision = "94381e463511"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
