"""test running migrations

Revision ID: 94381e463511
Revises: 9786c26c160b
Create Date: 2024-03-04 19:25:55.942777

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "94381e463511"
down_revision = "9786c26c160b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
