"""check_db

Revision ID: f33f237c8e79
Revises: 44d06b64441a
Create Date: 2024-03-12 20:48:59.389181

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "f33f237c8e79"
down_revision = "44d06b64441a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
